project:
  type: book

book:
  title: |
    Code and data for "master I project" about the protein structural divergence after gene and genome duplications
  author: 
    - name: Toon De Lange
      orcid: Your ORCID #  every researcher has unique orcid
  date: "year"
  chapters:
    - index.qmd
    - chapters/chapter_01.qmd
    
bibliography: bibliography.bib

execute:
  freeze: auto

format:
  html:
    theme: cosmo

editor: 
  mode: source